name: first workflow
on: push
jobs:
 build:
   name: hello world action
   runs-on: ubuntu-latest
   steps:
     - name: my-step
       run: echo "Hello World"
 test:
   name: test-action
   runs-on: ubuntu-latest
   steps:
     - name: my-test
       run: npm run ng test
       
 
