name: first workflow
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
 build:
   name: hello world action
   runs-on: ubuntu-latest
   steps:
     - name: my-step
       run: echo "Hello World"
 test:
   name: test-action
   runs-on: ubuntu-latest
   steps:
     - name: my-test
       run: npm install
            npm run ng test
       
 
